import { ToolbarProvider } from "./_context/ToolbarContext";
import "./style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  toolbar
}: {
  children: React.ReactNode,
  toolbar: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full h-screen relative">
          <ToolbarProvider>
            {toolbar}
            {children}
          </ToolbarProvider>
        </div>
      </body>
    </html>
  );
}
