import "../style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  toolbar
}: {
  children: React.ReactNode,
  toolbar: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex h-svh">
        {toolbar}
        {children}
      </body>
    </html>
  );
}
